services:
- docker
install: make build
stages:
- name: echo
- name: publish
  if: branch = main AND type != pull_request
jobs:
  include:
  - stage: echo
    script: echo
  - stage: publish
    name: Publish production image
    script:
    - docker login -u="$QUAY_USERNAME" -p="$QUAY_PASSWORD" quay.io
    - make publish
env:
  global:
  - secure: sRaK5PGZICUVXG8h7mEZqmNb/BPW5p+h6EgKnfLXM1nCtBFQGDfSYcYsLGE5QktOCV7UmZBtXYKbh+2xHNuCFzJXGyTR7GG+UNAJghirqFJ4cvzw4u2vwWPashCvjodvpDEhuLhWb46/8ZND3R+qer2z0kwzvMFESrKh4oWfdw68JGV6xhRaEjvXPB2tEOkJjSwsp7k3Ip6p2kI8PGw8YtGAFt4eBAl33qsnsx9X2Fqva9uwJ7iA3dJ9aa6al2jLwnZhk2qJ0ShPu22+IOO44jl5y6NMDxU2XmZGUnq4lF4/4Nc+dJs+OXliKdI8hGbowf317W766gu80x1eMzu1VEpblStqGHWLqFp23vG4oNL0xou1SlmJs7tSdgQOXo2n1YYHVyDWIKLHjCx5AbKGIeTWgrWERmYSL+3yJbw5hhxUHgVh2LO2zMJ9f/UrIf4Z3hY76YfEqPfItURHvgaJHPi1Yx4kPVBIP2ccCBB+cxg2aV1V1A/Vqu6S6Mfwi7fWyXg/Vt6gM0NweunBbzD4GZ3n0XmRQlSqt+eSG4V3/Bw583p2BMIw2BnnlpavBiN3dTAUivLm/k8PLfKQskVfn5AXYcbotZ5JBeBINAe8bDEqYWQZ+d492snB+Wq/XAOukr5m7hY+KOZ7IXKId7nfwmn986flX1qKdUW1gVZbfRM=
  - secure: yRDrou3TxFhNRVRgWG8DwA592+nPR9DGmUjgT97p2xP/asK+sIpcHrI/gDnrkay40v3tcpYt4GdccrV6/o8gAVSuy75Yv1kv3WT7u3SfkxT8EBWrW0xkKnUa/NT95wJbrTkVXxOJUY4qtUMShtNxTgs2ROOuhCkyl+TGpQU55Egxzz4wVKAi0HmVd3AqIyNm0VIkgQy016bfnOLjt7BrvSX4Mc+mJ2TKgpc6dfzSgBeUPn2zlwxSN7yGz12Bk9eV+4Qumwo1U6QcUqTZOLWl1gDE/MYXKH6xoVxBIyXdnYQLc0+I38yTKjhL1JYuwbgorhNonyzV4sowF3+uZZcoRVA/3zD4FmJIdonHfjZDpUg8jNlUFuI+C9r7RuOl02ghEdqN16tId/M1DXVn6oxvcvuudvaW5U60DkAvgfzNqWz9lsGUXZdgBv5+nMkewZs+gfU0y9PuSIwVQRa+Aa53FPvQsHO2tkhgkZTROaZXh5q05OwM4YbLPpHJczy2o7H4iP2e1ypdq4Q9lnmClO1IhTAHvi6t4rC8lmPSPFEzPrQtQa5fdClRmDUkTfbLm1aGYeDLNKjZ2rtImIncvK4BvCxd93ZeyfffalJLUhep4MsBSQR8GMCKVvroHf33/C29kW3rc9PD7cwRDeqJVAR3SATdXzPHixHHIKJBdorX+xY=
